def isOdd(x):
    if x==1:
        return True
    elif x==2:
        return False
    elif x==3:
        return True
    elif x==4:
        return False
    elif x==5:
        return True
    elif x==6:
        return False
    elif x==7:
        return True
    elif x==8:
        return False
    elif x==9:
        return True
    elif x==10:
        return False
    elif x==11:
        return True
    elif x==12:
        return False
    elif x==13:
        return True
    elif x==14:
        return False
    elif x==15:
        return True
    elif x==16:
        return False
    elif x==17:
        return True
    elif x==18:
        return False
    elif x==19:
        return True
    elif x==20:
        return False
    elif x==21:
        return True
    elif x==22:
        return False
    elif x==23:
        return True
    elif x==24:
        return False
    elif x==25:
        return True
    elif x==26:
        return False
    elif x==27:
        return True
    elif x==28:
        return False
    elif x==29:
        return True
    elif x==30:
        return False
    elif x==31:
        return True
    elif x==32:
        return False
    elif x==33:
        return True
    elif x==34:
        return False
    elif x==35:
        return True
    elif x==36:
        return False
    elif x==37:
        return True
    elif x==38:
        return False
    elif x==39:
        return True
    elif x==40:
        return False
    elif x==41:
        return True
    elif x==42:
        return False
    elif x==43:
        return True
    elif x==44:
        return False
    elif x==45:
        return True
    elif x==46:
        return False
    elif x==47:
        return True
    elif x==48:
        return False
    elif x==49:
        return True
    elif x==50:
        return False
    elif x==51:
        return True
    elif x==52:
        return False
    elif x==53:
        return True
    elif x==54:
        return False
    elif x==55:
        return True
    elif x==56:
        return False
    elif x==57:
        return True
    elif x==58:
        return False
    elif x==59:
        return True
    elif x==60:
        return False
    elif x==61:
        return True
    elif x==62:
        return False
    elif x==63:
        return True
    elif x==64:
        return False
    elif x==65:
        return True
    elif x==66:
        return False
    elif x==67:
        return True
    elif x==68:
        return False
    elif x==69:
        return True
    elif x==70:
        return False
    elif x==71:
        return True
    elif x==72:
        return False
    elif x==73:
        return True
    elif x==74:
        return False
    elif x==75:
        return True
    elif x==76:
        return False
    elif x==77:
        return True
    elif x==78:
        return False
    elif x==79:
        return True
    elif x==80:
        return False
    elif x==81:
        return True
    elif x==82:
        return False
    elif x==83:
        return True
    elif x==84:
        return False
    elif x==85:
        return True
    elif x==86:
        return False
    elif x==87:
        return True
    elif x==88:
        return False
    elif x==89:
        return True
    elif x==90:
        return False
    elif x==91:
        return True
    elif x==92:
        return False
    elif x==93:
        return True
    elif x==94:
        return False
    elif x==95:
        return True
    elif x==96:
        return False
    elif x==97:
        return True
    elif x==98:
        return False
    elif x==99:
        return True
    elif x==100:
        return False
    elif x==101:
        return True
    elif x==102:
        return False
    elif x==103:
        return True
    elif x==104:
        return False
    elif x==105:
        return True
    elif x==106:
        return False
    elif x==107:
        return True
    elif x==108:
        return False
    elif x==109:
        return True
    elif x==110:
        return False
    elif x==111:
        return True
    elif x==112:
        return False
    elif x==113:
        return True
    elif x==114:
        return False
    elif x==115:
        return True
    elif x==116:
        return False
    elif x==117:
        return True
    elif x==118:
        return False
    elif x==119:
        return True
    elif x==120:
        return False
    elif x==121:
        return True
    elif x==122:
        return False
    elif x==123:
        return True
    elif x==124:
        return False
    elif x==125:
        return True
    elif x==126:
        return False
    elif x==127:
        return True
    elif x==128:
        return False
    elif x==129:
        return True
    elif x==130:
        return False
    elif x==131:
        return True
    elif x==132:
        return False
    elif x==133:
        return True
    elif x==134:
        return False
    elif x==135:
        return True
    elif x==136:
        return False
    elif x==137:
        return True
    elif x==138:
        return False
    elif x==139:
        return True
    elif x==140:
        return False
    elif x==141:
        return True
    elif x==142:
        return False
    elif x==143:
        return True
    elif x==144:
        return False
    elif x==145:
        return True
    elif x==146:
        return False
    elif x==147:
        return True
    elif x==148:
        return False
    elif x==149:
        return True
    elif x==150:
        return False
    elif x==151:
        return True
    elif x==152:
        return False
    elif x==153:
        return True
    elif x==154:
        return False
    elif x==155:
        return True
    elif x==156:
        return False
    elif x==157:
        return True
    elif x==158:
        return False
    elif x==159:
        return True
    elif x==160:
        return False
    elif x==161:
        return True
    elif x==162:
        return False
    elif x==163:
        return True
    elif x==164:
        return False
    elif x==165:
        return True
    elif x==166:
        return False
    elif x==167:
        return True
    elif x==168:
        return False
    elif x==169:
        return True
    elif x==170:
        return False
    elif x==171:
        return True
    elif x==172:
        return False
    elif x==173:
        return True
    elif x==174:
        return False
    elif x==175:
        return True
    elif x==176:
        return False
    elif x==177:
        return True
    elif x==178:
        return False
    elif x==179:
        return True
    elif x==180:
        return False
    elif x==181:
        return True
    elif x==182:
        return False
    elif x==183:
        return True
    elif x==184:
        return False
    elif x==185:
        return True
    elif x==186:
        return False
    elif x==187:
        return True
    elif x==188:
        return False
    elif x==189:
        return True
    elif x==190:
        return False
    elif x==191:
        return True
    elif x==192:
        return False
    elif x==193:
        return True
    elif x==194:
        return False
    elif x==195:
        return True
    elif x==196:
        return False
    elif x==197:
        return True
    elif x==198:
        return False
    elif x==199:
        return True
    elif x==200:
        return False
    elif x==201:
        return True
    elif x==202:
        return False
    elif x==203:
        return True
    elif x==204:
        return False
    elif x==205:
        return True
    elif x==206:
        return False
    elif x==207:
        return True
    elif x==208:
        return False
    elif x==209:
        return True
    elif x==210:
        return False
    elif x==211:
        return True
    elif x==212:
        return False
    elif x==213:
        return True
    elif x==214:
        return False
    elif x==215:
        return True
    elif x==216:
        return False
    elif x==217:
        return True
    elif x==218:
        return False
    elif x==219:
        return True
    elif x==220:
        return False
    elif x==221:
        return True
    elif x==222:
        return False
    elif x==223:
        return True
    elif x==224:
        return False
    elif x==225:
        return True
    elif x==226:
        return False
    elif x==227:
        return True
    elif x==228:
        return False
    elif x==229:
        return True
    elif x==230:
        return False
    elif x==231:
        return True
    elif x==232:
        return False
    elif x==233:
        return True
    elif x==234:
        return False
    elif x==235:
        return True
    elif x==236:
        return False
    elif x==237:
        return True
    elif x==238:
        return False
    elif x==239:
        return True
    elif x==240:
        return False
    elif x==241:
        return True
    elif x==242:
        return False
    elif x==243:
        return True
    elif x==244:
        return False
    elif x==245:
        return True
    elif x==246:
        return False
    elif x==247:
        return True
    elif x==248:
        return False
    elif x==249:
        return True
    elif x==250:
        return False
    elif x==251:
        return True
    elif x==252:
        return False
    elif x==253:
        return True
    elif x==254:
        return False
    elif x==255:
        return True
    elif x==256:
        return False
    elif x==257:
        return True
    elif x==258:
        return False
    elif x==259:
        return True
    elif x==260:
        return False
    elif x==261:
        return True
    elif x==262:
        return False
    elif x==263:
        return True
    elif x==264:
        return False
    elif x==265:
        return True
    elif x==266:
        return False
    elif x==267:
        return True
    elif x==268:
        return False
    elif x==269:
        return True
    elif x==270:
        return False
    elif x==271:
        return True
    elif x==272:
        return False
    elif x==273:
        return True
    elif x==274:
        return False
    elif x==275:
        return True
    elif x==276:
        return False
    elif x==277:
        return True
    elif x==278:
        return False
    elif x==279:
        return True
    elif x==280:
        return False
    elif x==281:
        return True
    elif x==282:
        return False
    elif x==283:
        return True
    elif x==284:
        return False
    elif x==285:
        return True
    elif x==286:
        return False
    elif x==287:
        return True
    elif x==288:
        return False
    elif x==289:
        return True
    elif x==290:
        return False
    elif x==291:
        return True
    elif x==292:
        return False
    elif x==293:
        return True
    elif x==294:
        return False
    elif x==295:
        return True
    elif x==296:
        return False
    elif x==297:
        return True
    elif x==298:
        return False
    elif x==299:
        return True
    elif x==300:
        return False
    elif x==301:
        return True
    elif x==302:
        return False
    elif x==303:
        return True
    elif x==304:
        return False
    elif x==305:
        return True
    elif x==306:
        return False
    elif x==307:
        return True
    elif x==308:
        return False
    elif x==309:
        return True
    elif x==310:
        return False
    elif x==311:
        return True
    elif x==312:
        return False
    elif x==313:
        return True
    elif x==314:
        return False
    elif x==315:
        return True
    elif x==316:
        return False
    elif x==317:
        return True
    elif x==318:
        return False
    elif x==319:
        return True
    elif x==320:
        return False
    elif x==321:
        return True
    elif x==322:
        return False
    elif x==323:
        return True
    elif x==324:
        return False
    elif x==325:
        return True
    elif x==326:
        return False
    elif x==327:
        return True
    elif x==328:
        return False
    elif x==329:
        return True
    elif x==330:
        return False
    elif x==331:
        return True
    elif x==332:
        return False
    elif x==333:
        return True
    elif x==334:
        return False
    elif x==335:
        return True
    elif x==336:
        return False
    elif x==337:
        return True
    elif x==338:
        return False
    elif x==339:
        return True
    elif x==340:
        return False
    elif x==341:
        return True
    elif x==342:
        return False
    elif x==343:
        return True
    elif x==344:
        return False
    elif x==345:
        return True
    elif x==346:
        return False
    elif x==347:
        return True
    elif x==348:
        return False
    elif x==349:
        return True
    elif x==350:
        return False
    elif x==351:
        return True
    elif x==352:
        return False
    elif x==353:
        return True
    elif x==354:
        return False
    elif x==355:
        return True
    elif x==356:
        return False
    elif x==357:
        return True
    elif x==358:
        return False
    elif x==359:
        return True
    elif x==360:
        return False
    elif x==361:
        return True
    elif x==362:
        return False
    elif x==363:
        return True
    elif x==364:
        return False
    elif x==365:
        return True
    elif x==366:
        return False
    elif x==367:
        return True
    elif x==368:
        return False
    elif x==369:
        return True
    elif x==370:
        return False
    elif x==371:
        return True
    elif x==372:
        return False
    elif x==373:
        return True
    elif x==374:
        return False
    elif x==375:
        return True
    elif x==376:
        return False
    elif x==377:
        return True
    elif x==378:
        return False
    elif x==379:
        return True
    elif x==380:
        return False
    elif x==381:
        return True
    elif x==382:
        return False
    elif x==383:
        return True
    elif x==384:
        return False
    elif x==385:
        return True
    elif x==386:
        return False
    elif x==387:
        return True
    elif x==388:
        return False
    elif x==389:
        return True
    elif x==390:
        return False
    elif x==391:
        return True
    elif x==392:
        return False
    elif x==393:
        return True
    elif x==394:
        return False
    elif x==395:
        return True
    elif x==396:
        return False
    elif x==397:
        return True
    elif x==398:
        return False
    elif x==399:
        return True
    elif x==400:
        return False
    elif x==401:
        return True
    elif x==402:
        return False
    elif x==403:
        return True
    elif x==404:
        return False
    elif x==405:
        return True
    elif x==406:
        return False
    elif x==407:
        return True
    elif x==408:
        return False
    elif x==409:
        return True
    elif x==410:
        return False
    elif x==411:
        return True
    elif x==412:
        return False
    elif x==413:
        return True
    elif x==414:
        return False
    elif x==415:
        return True
    elif x==416:
        return False
    elif x==417:
        return True
    elif x==418:
        return False
    elif x==419:
        return True
    elif x==420:
        return False
    elif x==421:
        return True
    elif x==422:
        return False
    elif x==423:
        return True
    elif x==424:
        return False
    elif x==425:
        return True
    elif x==426:
        return False
    elif x==427:
        return True
    elif x==428:
        return False
    elif x==429:
        return True
    elif x==430:
        return False
    elif x==431:
        return True
    elif x==432:
        return False
    elif x==433:
        return True
    elif x==434:
        return False
    elif x==435:
        return True
    elif x==436:
        return False
    elif x==437:
        return True
    elif x==438:
        return False
    elif x==439:
        return True
    elif x==440:
        return False
    elif x==441:
        return True
    elif x==442:
        return False
    elif x==443:
        return True
    elif x==444:
        return False
    elif x==445:
        return True
    elif x==446:
        return False
    elif x==447:
        return True
    elif x==448:
        return False
    elif x==449:
        return True
    elif x==450:
        return False
    elif x==451:
        return True
    elif x==452:
        return False
    elif x==453:
        return True
    elif x==454:
        return False
    elif x==455:
        return True
    elif x==456:
        return False
    elif x==457:
        return True
    elif x==458:
        return False
    elif x==459:
        return True
    elif x==460:
        return False
    elif x==461:
        return True
    elif x==462:
        return False
    elif x==463:
        return True
    elif x==464:
        return False
    elif x==465:
        return True
    elif x==466:
        return False
    elif x==467:
        return True
    elif x==468:
        return False
    elif x==469:
        return True
    elif x==470:
        return False
    elif x==471:
        return True
    elif x==472:
        return False
    elif x==473:
        return True
    elif x==474:
        return False
    elif x==475:
        return True
    elif x==476:
        return False
    elif x==477:
        return True
    elif x==478:
        return False
    elif x==479:
        return True
    elif x==480:
        return False
    elif x==481:
        return True
    elif x==482:
        return False
    elif x==483:
        return True
    elif x==484:
        return False
    elif x==485:
        return True
    elif x==486:
        return False
    elif x==487:
        return True
    elif x==488:
        return False
    elif x==489:
        return True
    elif x==490:
        return False
    elif x==491:
        return True
    elif x==492:
        return False
    elif x==493:
        return True
    elif x==494:
        return False
    elif x==495:
        return True
    elif x==496:
        return False
    elif x==497:
        return True
    elif x==498:
        return False
    elif x==499:
        return True
    elif x==500:
        return False
    elif x==501:
        return True
    elif x==502:
        return False
    elif x==503:
        return True
    elif x==504:
        return False
    elif x==505:
        return True
    elif x==506:
        return False
    elif x==507:
        return True
    elif x==508:
        return False
    elif x==509:
        return True
    elif x==510:
        return False
    elif x==511:
        return True
    elif x==512:
        return False
    elif x==513:
        return True
    elif x==514:
        return False
    elif x==515:
        return True
    elif x==516:
        return False
    elif x==517:
        return True
    elif x==518:
        return False
    elif x==519:
        return True
    elif x==520:
        return False
    elif x==521:
        return True
    elif x==522:
        return False
    elif x==523:
        return True
    elif x==524:
        return False
    elif x==525:
        return True
    elif x==526:
        return False
    elif x==527:
        return True
    elif x==528:
        return False
    elif x==529:
        return True
    elif x==530:
        return False
    elif x==531:
        return True
    elif x==532:
        return False
    elif x==533:
        return True
    elif x==534:
        return False
    elif x==535:
        return True
    elif x==536:
        return False
    elif x==537:
        return True
    elif x==538:
        return False
    elif x==539:
        return True
    elif x==540:
        return False
    elif x==541:
        return True
    elif x==542:
        return False
    elif x==543:
        return True
    elif x==544:
        return False
    elif x==545:
        return True
    elif x==546:
        return False
    elif x==547:
        return True
    elif x==548:
        return False
    elif x==549:
        return True
    elif x==550:
        return False
    elif x==551:
        return True
    elif x==552:
        return False
    elif x==553:
        return True
    elif x==554:
        return False
    elif x==555:
        return True
    elif x==556:
        return False
    elif x==557:
        return True
    elif x==558:
        return False
    elif x==559:
        return True
    elif x==560:
        return False
    elif x==561:
        return True
    elif x==562:
        return False
    elif x==563:
        return True
    elif x==564:
        return False
    elif x==565:
        return True
    elif x==566:
        return False
    elif x==567:
        return True
    elif x==568:
        return False
    elif x==569:
        return True
    elif x==570:
        return False
    elif x==571:
        return True
    elif x==572:
        return False
    elif x==573:
        return True
    elif x==574:
        return False
    elif x==575:
        return True
    elif x==576:
        return False
    elif x==577:
        return True
    elif x==578:
        return False
    elif x==579:
        return True
    elif x==580:
        return False
    elif x==581:
        return True
    elif x==582:
        return False
    elif x==583:
        return True
    elif x==584:
        return False
    elif x==585:
        return True
    elif x==586:
        return False
    elif x==587:
        return True
    elif x==588:
        return False
    elif x==589:
        return True
    elif x==590:
        return False
    elif x==591:
        return True
    elif x==592:
        return False
    elif x==593:
        return True
    elif x==594:
        return False
    elif x==595:
        return True
    elif x==596:
        return False
    elif x==597:
        return True
    elif x==598:
        return False
    elif x==599:
        return True
    elif x==600:
        return False
    elif x==601:
        return True
    elif x==602:
        return False
    elif x==603:
        return True
    elif x==604:
        return False
    elif x==605:
        return True
    elif x==606:
        return False
    elif x==607:
        return True
    elif x==608:
        return False
    elif x==609:
        return True
    elif x==610:
        return False
    elif x==611:
        return True
    elif x==612:
        return False
    elif x==613:
        return True
    elif x==614:
        return False
    elif x==615:
        return True
    elif x==616:
        return False
    elif x==617:
        return True
    elif x==618:
        return False
    elif x==619:
        return True
    elif x==620:
        return False
    elif x==621:
        return True
    elif x==622:
        return False
    elif x==623:
        return True
    elif x==624:
        return False
    elif x==625:
        return True
    elif x==626:
        return False
    elif x==627:
        return True
    elif x==628:
        return False
    elif x==629:
        return True
    elif x==630:
        return False
    elif x==631:
        return True
    elif x==632:
        return False
    elif x==633:
        return True
    elif x==634:
        return False
    elif x==635:
        return True
    elif x==636:
        return False
    elif x==637:
        return True
    elif x==638:
        return False
    elif x==639:
        return True
    elif x==640:
        return False
    elif x==641:
        return True
    elif x==642:
        return False
    elif x==643:
        return True
    elif x==644:
        return False
    elif x==645:
        return True
    elif x==646:
        return False
    elif x==647:
        return True
    elif x==648:
        return False
    elif x==649:
        return True
    elif x==650:
        return False
    elif x==651:
        return True
    elif x==652:
        return False
    elif x==653:
        return True
    elif x==654:
        return False
    elif x==655:
        return True
    elif x==656:
        return False
    elif x==657:
        return True
    elif x==658:
        return False
    elif x==659:
        return True
    elif x==660:
        return False
    elif x==661:
        return True
    elif x==662:
        return False
    elif x==663:
        return True
    elif x==664:
        return False
    elif x==665:
        return True
    elif x==666:
        return False
    elif x==667:
        return True
    elif x==668:
        return False
    elif x==669:
        return True
    elif x==670:
        return False
    elif x==671:
        return True
    elif x==672:
        return False
    elif x==673:
        return True
    elif x==674:
        return False
    elif x==675:
        return True
    elif x==676:
        return False
    elif x==677:
        return True
    elif x==678:
        return False
    elif x==679:
        return True
    elif x==680:
        return False
    elif x==681:
        return True
    elif x==682:
        return False
    elif x==683:
        return True
    elif x==684:
        return False
    elif x==685:
        return True
    elif x==686:
        return False
    elif x==687:
        return True
    elif x==688:
        return False
    elif x==689:
        return True
    elif x==690:
        return False
    elif x==691:
        return True
    elif x==692:
        return False
    elif x==693:
        return True
    elif x==694:
        return False
    elif x==695:
        return True
    elif x==696:
        return False
    elif x==697:
        return True
    elif x==698:
        return False
    elif x==699:
        return True
    elif x==700:
        return False
    elif x==701:
        return True
    elif x==702:
        return False
    elif x==703:
        return True
    elif x==704:
        return False
    elif x==705:
        return True
    elif x==706:
        return False
    elif x==707:
        return True
    elif x==708:
        return False
    elif x==709:
        return True
    elif x==710:
        return False
    elif x==711:
        return True
    elif x==712:
        return False
    elif x==713:
        return True
    elif x==714:
        return False
    elif x==715:
        return True
    elif x==716:
        return False
    elif x==717:
        return True
    elif x==718:
        return False
    elif x==719:
        return True
    elif x==720:
        return False
    elif x==721:
        return True
    elif x==722:
        return False
    elif x==723:
        return True
    elif x==724:
        return False
    elif x==725:
        return True
    elif x==726:
        return False
    elif x==727:
        return True
    elif x==728:
        return False
    elif x==729:
        return True
    elif x==730:
        return False
    elif x==731:
        return True
    elif x==732:
        return False
    elif x==733:
        return True
    elif x==734:
        return False
    elif x==735:
        return True
    elif x==736:
        return False
    elif x==737:
        return True
    elif x==738:
        return False
    elif x==739:
        return True
    elif x==740:
        return False
    elif x==741:
        return True
    elif x==742:
        return False
    elif x==743:
        return True
    elif x==744:
        return False
    elif x==745:
        return True
    elif x==746:
        return False
    elif x==747:
        return True
    elif x==748:
        return False
    elif x==749:
        return True
    elif x==750:
        return False
    elif x==751:
        return True
    elif x==752:
        return False
    elif x==753:
        return True
    elif x==754:
        return False
    elif x==755:
        return True
    elif x==756:
        return False
    elif x==757:
        return True
    elif x==758:
        return False
    elif x==759:
        return True
    elif x==760:
        return False
    elif x==761:
        return True
    elif x==762:
        return False
    elif x==763:
        return True
    elif x==764:
        return False
    elif x==765:
        return True
    elif x==766:
        return False
    elif x==767:
        return True
    elif x==768:
        return False
    elif x==769:
        return True
    elif x==770:
        return False
    elif x==771:
        return True
    elif x==772:
        return False
    elif x==773:
        return True
    elif x==774:
        return False
    elif x==775:
        return True
    elif x==776:
        return False
    elif x==777:
        return True
    elif x==778:
        return False
    elif x==779:
        return True
    elif x==780:
        return False
    elif x==781:
        return True
    elif x==782:
        return False
    elif x==783:
        return True
    elif x==784:
        return False
    elif x==785:
        return True
    elif x==786:
        return False
    elif x==787:
        return True
    elif x==788:
        return False
    elif x==789:
        return True
    elif x==790:
        return False
    elif x==791:
        return True
    elif x==792:
        return False
    elif x==793:
        return True
    elif x==794:
        return False
    elif x==795:
        return True
    elif x==796:
        return False
    elif x==797:
        return True
    elif x==798:
        return False
    elif x==799:
        return True
    elif x==800:
        return False
    elif x==801:
        return True
    elif x==802:
        return False
    elif x==803:
        return True
    elif x==804:
        return False
    elif x==805:
        return True
    elif x==806:
        return False
    elif x==807:
        return True
    elif x==808:
        return False
    elif x==809:
        return True
    elif x==810:
        return False
    elif x==811:
        return True
    elif x==812:
        return False
    elif x==813:
        return True
    elif x==814:
        return False
    elif x==815:
        return True
    elif x==816:
        return False
    elif x==817:
        return True
    elif x==818:
        return False
    elif x==819:
        return True
    elif x==820:
        return False
    elif x==821:
        return True
    elif x==822:
        return False
    elif x==823:
        return True
    elif x==824:
        return False
    elif x==825:
        return True
    elif x==826:
        return False
    elif x==827:
        return True
    elif x==828:
        return False
    elif x==829:
        return True
    elif x==830:
        return False
    elif x==831:
        return True
    elif x==832:
        return False
    elif x==833:
        return True
    elif x==834:
        return False
    elif x==835:
        return True
    elif x==836:
        return False
    elif x==837:
        return True
    elif x==838:
        return False
    elif x==839:
        return True
    elif x==840:
        return False
    elif x==841:
        return True
    elif x==842:
        return False
    elif x==843:
        return True
    elif x==844:
        return False
    elif x==845:
        return True
    elif x==846:
        return False
    elif x==847:
        return True
    elif x==848:
        return False
    elif x==849:
        return True
    elif x==850:
        return False
    elif x==851:
        return True
    elif x==852:
        return False
    elif x==853:
        return True
    elif x==854:
        return False
    elif x==855:
        return True
    elif x==856:
        return False
    elif x==857:
        return True
    elif x==858:
        return False
    elif x==859:
        return True
    elif x==860:
        return False
    elif x==861:
        return True
    elif x==862:
        return False
    elif x==863:
        return True
    elif x==864:
        return False
    elif x==865:
        return True
    elif x==866:
        return False
    elif x==867:
        return True
    elif x==868:
        return False
    elif x==869:
        return True
    elif x==870:
        return False
    elif x==871:
        return True
    elif x==872:
        return False
    elif x==873:
        return True
    elif x==874:
        return False
    elif x==875:
        return True
    elif x==876:
        return False
    elif x==877:
        return True
    elif x==878:
        return False
    elif x==879:
        return True
    elif x==880:
        return False
    elif x==881:
        return True
    elif x==882:
        return False
    elif x==883:
        return True
    elif x==884:
        return False
    elif x==885:
        return True
    elif x==886:
        return False
    elif x==887:
        return True
    elif x==888:
        return False
    elif x==889:
        return True
    elif x==890:
        return False
    elif x==891:
        return True
    elif x==892:
        return False
    elif x==893:
        return True
    elif x==894:
        return False
    elif x==895:
        return True
    elif x==896:
        return False
    elif x==897:
        return True
    elif x==898:
        return False
    elif x==899:
        return True
    elif x==900:
        return False
    elif x==901:
        return True
    elif x==902:
        return False
    elif x==903:
        return True
    elif x==904:
        return False
    elif x==905:
        return True
    elif x==906:
        return False
    elif x==907:
        return True
    elif x==908:
        return False
    elif x==909:
        return True
    elif x==910:
        return False
    elif x==911:
        return True
    elif x==912:
        return False
    elif x==913:
        return True
    elif x==914:
        return False
    elif x==915:
        return True
    elif x==916:
        return False
    elif x==917:
        return True
    elif x==918:
        return False
    elif x==919:
        return True
    elif x==920:
        return False
    elif x==921:
        return True
    elif x==922:
        return False
    elif x==923:
        return True
    elif x==924:
        return False
    elif x==925:
        return True
    elif x==926:
        return False
    elif x==927:
        return True
    elif x==928:
        return False
    elif x==929:
        return True
    elif x==930:
        return False
    elif x==931:
        return True
    elif x==932:
        return False
    elif x==933:
        return True
    elif x==934:
        return False
    elif x==935:
        return True
    elif x==936:
        return False
    elif x==937:
        return True
    elif x==938:
        return False
    elif x==939:
        return True
    elif x==940:
        return False
    elif x==941:
        return True
    elif x==942:
        return False
    elif x==943:
        return True
    elif x==944:
        return False
    elif x==945:
        return True
    elif x==946:
        return False
    elif x==947:
        return True
    elif x==948:
        return False
    elif x==949:
        return True
    elif x==950:
        return False
    elif x==951:
        return True
    elif x==952:
        return False
    elif x==953:
        return True
    elif x==954:
        return False
    elif x==955:
        return True
    elif x==956:
        return False
    elif x==957:
        return True
    elif x==958:
        return False
    elif x==959:
        return True
    elif x==960:
        return False
    elif x==961:
        return True
    elif x==962:
        return False
    elif x==963:
        return True
    elif x==964:
        return False
    elif x==965:
        return True
    elif x==966:
        return False
    elif x==967:
        return True
    elif x==968:
        return False
    elif x==969:
        return True
    elif x==970:
        return False
    elif x==971:
        return True
    elif x==972:
        return False
    elif x==973:
        return True
    elif x==974:
        return False
    elif x==975:
        return True
    elif x==976:
        return False
    elif x==977:
        return True
    elif x==978:
        return False
    elif x==979:
        return True
    elif x==980:
        return False
    elif x==981:
        return True
    elif x==982:
        return False
    elif x==983:
        return True
    elif x==984:
        return False
    elif x==985:
        return True
    elif x==986:
        return False
    elif x==987:
        return True
    elif x==988:
        return False
    elif x==989:
        return True
    elif x==990:
        return False
    elif x==991:
        return True
    elif x==992:
        return False
    elif x==993:
        return True
    elif x==994:
        return False
    elif x==995:
        return True
    elif x==996:
        return False
    elif x==997:
        return True
    elif x==998:
        return False
    elif x==999:
        return True
    elif x==1000:
        return False
